package store

import (
	"fmt"
	"sort"
	"strings"

	"github.com/tshubham2/code-mem/internal/index"
)

// Boot index limits keep its size roughly constant as the corpus grows.
const (
	bootClusters = 20 // clusters listed before "+N more"
	bootPerGroup = 3  // memories named per cluster
)

// BootIndex renders the always-in-context index: one line per cluster with
// its size and its best-connected memories. Slugs are listed rather than
// prose because they are exactly what mem_get takes.
func BootIndex(label string, x *index.Index) string {
	type group struct {
		name string
		ids  []uint32
	}
	byName := map[string]*group{}
	var groups []*group
	for id := uint32(0); id < uint32(x.Real()); id++ {
		c := x.Cluster(id)
		g := byName[c]
		if g == nil {
			g = &group{name: c}
			byName[c] = g
			groups = append(groups, g)
		}
		g.ids = append(g.ids, id)
	}
	sort.Slice(groups, func(i, j int) bool {
		if len(groups[i].ids) != len(groups[j].ids) {
			return len(groups[i].ids) > len(groups[j].ids)
		}
		return groups[i].name < groups[j].name
	})

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — %d %s\n\n", label, x.Real(), plural(x.Real(), "memory", "memories"))
	if x.Real() == 0 {
		b.WriteString("(none yet — save one with mem_save)\n")
	}
	for i, g := range groups {
		if i == bootClusters {
			fmt.Fprintf(&b, "- … %d more clusters (use mem_search)\n", len(groups)-i)
			break
		}
		degree := func(id uint32) int { return x.Out(id).Len() + x.In(id).Len() }
		sort.SliceStable(g.ids, func(i, j int) bool { return degree(g.ids[i]) > degree(g.ids[j]) })
		var names []string
		for _, id := range g.ids[:min(len(g.ids), bootPerGroup)] {
			names = append(names, x.Name(id))
		}
		line := strings.Join(names, ", ")
		if extra := len(g.ids) - len(names); extra > 0 {
			line += fmt.Sprintf(", +%d more", extra)
		}
		fmt.Fprintf(&b, "- **%s** (%d) — %s\n", g.name, len(g.ids), line)
	}
	b.WriteString("\n<!-- generated by code-mem; do not edit by hand -->\n")
	return b.String()
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}
